name: github-pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and deploy the demo site to GitHub Pages
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10.22.0

      - run: yarn install

      - name: Build
        run: yarn generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
